Account name fetch
OpenZeppelin/compound-monitoring pull request #169
Opened 2023-04-10 13:45 UTC by morganjweaver

2023-04-15 03:21 UTC, jbass-oz requested changes
Requested a couple changes and reviewed some of the files.  I have not run the tests yet. 
 I noticed remaining Todos.  I'll review again at a later commit.

2023-04-15 03:21 UTC, jbass-oz commented on defender/secret-example.yml
Please revert changes to this file so we can keep a list of secrets and their stacks.

2023-05-01 18:29 UTC, arbitrary-echo reviewed
Quick note about the Tally API key present in a script.

2023-05-02 01:08 UTC, morganjweaver commented on defender/forta_governance/testScript.js
> +const tallyApiKey = 'f38a52dd428c9893d63862b60ebf94f3c0f1f93b117f35b9d0f48a0dd8fae616';
file deleted, key inconsequential.  thanks!

2023-05-16 23:55 UTC, jbass-oz requested changes
some changes requested.  closure not necessary at this time.  will review again tomorrow

2023-05-16 23:55 UTC, jbass-oz commented on defender/forta_governance/autotask-1/index.js
This seems like a good use case for a closure to set an apikey variable outside the scope of the handler function for reuse by other functions.  A getter method could check if a private variable is valid and throw if not.  The apikey would not need to be added as a parameter to the functions.

2023-05-16 23:55 UTC, jbass-oz commented on defender/governance_discord_alert/autotask-1/index.js
This seems like a good use case for a closure to set an apikey variable outside the scope of the handler function for reuse by other functions. A getter method could check if a private variable is valid and throw if not. The apikey would not need to be added as a parameter to the functions.

2023-05-16 23:55 UTC, jbass-oz commented on defender/governance_discord_alert/serverless.yml
> +   # - "0xc0Da02939E1441F497fd74F78cE7Decb17B66529"
remove line instead of comment

2023-05-16 23:55 UTC, jbass-oz commented on defender/governance_discord_alert/serverless.yml
> +  monitored-network: goerli #mainnet
remove comment

2023-05-16 23:55 UTC, jbass-oz commented on defender/secret-example.yml
revert

2023-05-16 23:55 UTC, jbass-oz commented on defender/tests/onChainResources/deployDummyGovernor.ts
is the empty file necessary?

2023-05-17 17:09 UTC, morganjweaver commented on defender/governance_discord_alert/autotask-1/index.js
Passing the var around is a little messy, isn't it?  Can you point to an example of this in Defender?  I know closures check for existing env context--would it look something like a helper function like:

```
function getTallyApiKey(){
  return secrets[tallyApiKeySecretName];
}
```
Then on init we check the getter for `undefined` and otherwise use when needed?

2023-05-17 17:09 UTC, morganjweaver commented on defender/forta_governance/autotask-1/index.js
See governance_discord_alert comment (identical to what I'd write here)

2023-05-17 18:04 UTC, morganjweaver commented on defender/tests/onChainResources/deployDummyGovernor.ts
deleted

2023-05-26 17:13 UTC, merged