SOL-312 price oracle source control
OpenZeppelin/compound-monitoring pull request #180
Opened 2023-06-07 17:19 UTC by morganjweaver

2023-06-30 11:02 UTC, jbass-oz requested changes
Add notification channel and update plugin

2023-06-30 11:02 UTC, jbass-oz commented on defender/forta_oracle_price/serverless.yml
Please add the notification channel in this serverless so that all references can be resolved if not already deployed.  Naming convention used in other recent serverless change should work with stackname.discord.
According to recent updates to serverless and defender, the sentinel trigger type should be supported with the '@openzeppelin/defender-serverless' plugin. Also we should update the serverless to use the latest defender-serverless plugin.  I think I have mine updated but I'm still troubleshooting issues.

2023-07-03 12:09 UTC, morganjweaver commented on defender/forta_oracle_price/serverless.yml
So the current discord channel is set to ` ${self:resources.Resources.notifications.discord}`; I think I need to include it in the resources list so that Defender understands the component is a Discord channel with name `'${self:custom.name} Security Alerts'`.  Is that ok?

2023-07-03 12:09 UTC, morganjweaver commented
Assuming Discord config is ok, I think it's ready to merge.

2023-07-04 13:10 UTC, jbass-oz approved these changes

2023-07-04 13:10 UTC, jbass-oz commented on defender/forta_oracle_price/serverless.yml
I changed the name of the channel

2023-07-04 13:11 UTC, jbass-oz approved these changes

2023-07-06 15:27 UTC, closed without merging